{
	".GlobalPreferences"."com.apple.mouse.scaling" = 0.875;
	ActivityMonitor.IconType = 6; # Show CPU history
	ActivityMonitor.OpenMainWindow = true;
	ActivityMonitor.ShowCategory = 101; # All Processes, Hierarchally
	ActivityMonitor.SortColumn = "CPUUsage";
	ActivityMonitor.SortDirection = 0; # Descending
	LaunchServices.LSQuarantine = false;
	NSGlobalDomain.AppleEnableMouseSwipeNavigateWithScrolls = true;
	NSGlobalDomain.AppleEnableSwipeNavigateWithScrolls = true;
	NSGlobalDomain.AppleFontSmoothing = null;
	NSGlobalDomain.AppleICUForce24HourTime = true;
	NSGlobalDomain.AppleInterfaceStyle = "Dark";
	NSGlobalDomain.AppleInterfaceStyleSwitchesAutomatically = false;
	NSGlobalDomain.AppleMeasurementUnits = "Centimeters";
	NSGlobalDomain.AppleMetricUnits = 1;
	NSGlobalDomain.ApplePressAndHoldEnabled = true;
	NSGlobalDomain.AppleShowAllExtensions = true;
	NSGlobalDomain.AppleShowAllFiles = false;
	NSGlobalDomain.AppleShowScrollBars = "WhenScrolling";
	NSGlobalDomain.AppleTemperatureUnit = "Celsius";
	NSGlobalDomain.InitialKeyRepeat = 12;
	NSGlobalDomain.KeyRepeat = 1;
	NSGlobalDomain.NSAutomaticCapitalizationEnabled = false;
	NSGlobalDomain.NSAutomaticDashSubstitutionEnabled = false;
	NSGlobalDomain.NSAutomaticInlinePredictionEnabled = true;
	NSGlobalDomain.NSAutomaticPeriodSubstitutionEnabled = false;
	NSGlobalDomain.NSAutomaticQuoteSubstitutionEnabled = false;
	NSGlobalDomain.NSAutomaticSpellingCorrectionEnabled = false;
	NSGlobalDomain.NSAutomaticWindowAnimationsEnabled = true;
	NSGlobalDomain.NSDocumentSaveNewDocumentsToCloud = false;
	NSGlobalDomain.NSNavPanelExpandedStateForSaveMode = true;
	NSGlobalDomain.NSNavPanelExpandedStateForSaveMode2 = true;
	NSGlobalDomain.NSScrollAnimationEnabled = true;
	NSGlobalDomain.NSTableViewDefaultSizeMode = 3;
	NSGlobalDomain.NSWindowShouldDragOnGesture = false;
	NSGlobalDomain._HIHideMenuBar = true;
	NSGlobalDomain."com.apple.keyboard.fnState" = false;
	NSGlobalDomain."com.apple.mouse.tapBehavior" = 1;
	NSGlobalDomain."com.apple.mouse.linear" = false;
	NSGlobalDomain."com.apple.swipescrolldirection" = true;

	SoftwareUpdate.AutomaticallyInstallMacOSUpdates = true;
	WindowManager.EnableStandardClickToShowDesktop = false;
	WindowManager.GloballyEnabled = false;
	dock = {
		enable-spring-load-actions-on-all-items = false;
		appswitcher-all-displays = true;
		autohide = true;
		autohide-delay = 0.20;
		autohide-time-modifier = 1.0;
		largesize = 16;
		launchanim = true;
		magnification = false;
		mineffect = "genie";
		minimize-to-application = true;
		mru-spaces = false;
		orientation = "left";
		persistent-apps = [
			"/System/Volumes/Data/Applications/Arc.app"
		];
		persistent-others = null;
		show-process-indicators = true;
		show-recents = false;
		showhidden = true;
		slow-motion-allowed = false;
		tilesize = 43;
		wvous-bl-corner = 1;
		wvous-br-corner = 1;
		wvous-tl-corner = 1;
		wvous-tr-corner = 1;
	};
	finder = {
		AppleShowAllExtensions = true;
		AppleShowAllFiles = false;
		CreateDesktop = true;
		FXDefaultSearchScope = "SCcf";
		FXEnableExtensionChangeWarning = false;
		FXPreferredViewStyle = "clmv";
		QuitMenuItem = false;
		ShowPathbar = true;
		ShowStatusBar = true;
		_FXShowPosixPathInTitle = false;
		_FXSortFoldersFirst = true;
	};
	loginwindow.DisableConsoleAccess = true;
	loginwindow.GuestEnabled = false;
	menuExtraClock.IsAnalog = false;
	menuExtraClock.Show24Hour = true;
	menuExtraClock.ShowAMPM = false;
	menuExtraClock.ShowDate = 1;
	menuExtraClock.ShowDayOfMonth = true;
	menuExtraClock.ShowDayOfWeek = true;
	menuExtraClock.ShowSeconds = false;
	screencapture.show-thumbnail = false;
	screensaver.askForPassword = true;
	spaces.spans-displays = false;
	trackpad.ActuationStrength = 0;
	trackpad.Clicking = true;
	trackpad.Dragging = false;
	trackpad.TrackpadRightClick = true;
	trackpad.TrackpadThreeFingerDrag = false;
	trackpad.TrackpadThreeFingerTapGesture = 0;
}
