#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"
source "$DOTFILES_PATH/scripts/codely/src/codely.sh"

##? Copy a CodelyTV Pro Course to the clipboard
#?? 1.0.0
##?
##? Usage:
##?   open_course
docs::parse "$@"

courses=$(codely::list_courses)

selected_index=$(echo "$courses" | awk -F';' '{print $2}' | choose -i)

echo "$courses" |
  sed -n "$((selected_index + 1))"p |
  awk -F';' '{print $1}' |
  tr -d '\n' |
  pbcopy
