#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Open a CodelyTV Pro Course
#?? 1.0.0
##?
##? Usage:
##?   open_course
docs::eval "$@"

# fzf version
#curl -s 'https://pro.codely.tv/api/private/library/resource/?page_size=50&page=1&ordering=featured&order=featured&type=course&filters%5Border%5D=featured&filters%5Btype%5D=course' |
#  jq -j '.results | .[] |.url,";", .name,"\n"' |
#  sed 's/"//g' |
#  fzf -d';' --with-nth 2 |
#  awk -F';' '{print $1}' |
#  xargs open

# choose version
courses=$(
  curl -s 'https://pro.codely.tv/api/private/library/resource/?page_size=50&page=1&ordering=featured&order=featured&type=course&filters%5Border%5D=featured&filters%5Btype%5D=course' |
    jq -j '.results | .[] |.url,";", .name,"\n"' |
    sed 's/"//g'
)

selected_index=$(echo "$courses" | awk -F';' '{print $2}' | choose -i)

echo "$courses" |
  sed -n "$((selected_index + 1))"p |
  awk -F';' '{print $1}' |
  xargs open
