#!/usr/bin/env bash

set -euo pipefail

##? Setups the environment
#?? 1.0.0
##?
##? Usage:
##?    install

echo "🚀 Welcome to the rgomezcasas/dotfiles installer!"
echo "-------------------------------------------------"
echo
read -rp "🤔  Where do you want to clone the dotfiles? (default ~/.dotfiles): " dotfiles_path
echo
#dotfiles_path="${dotfiles_path:-~/.dotfiles}"
dotfiles_path="$HOME/.dotfiles"
echo "👉  Cloning into: '$dotfiles_path'"

git clone git@github.com:rgomezcasas/dotfiles.git "$dotfiles_path"

"$dotfiles_path/bin/dot self install"
