{
  enable = true;
  taps = [  "manaflow-ai/cmux" ];
  brews = [
    "agent-browser"
    "ast-grep"
    "bitwarden-cli"
    "choose-gui"
    "cliclick"
    "gemini-cli"
    "jetbrains/junie/junie"
    "ollama"
    "sst/tap/opencode"
    "switchaudio-osx"
    "yt-dlp"
  ];
  casks = [
    "adobe-creative-cloud"
    "arc"
    "betterdisplay"
    "bettermouse"
    "bitwarden"
    "claude"
    "cloudflare-warp"
    "codex"
    "contexts"
    "cursor"
    "displaylink"
    "elgato-camera-hub"
    "elgato-control-center"
    "elgato-stream-deck"
    "elgato-wave-link"
    "figma"
    "ghostty@tip"
    "google-chrome"
    "google-chrome@canary"
    "google-drive"
    "grandperspective"
    "handbrake-app"
    "imaging-edge"
    "jetbrains-toolbox"
    "karabiner-elements"
    "manaflow-ai/cmux/cmux"
    "meld-studio"
    "mitmproxy"
    "mqtt-explorer"
    "notion"
    "obs"
    "orbstack"
    "orion"
    "raycast"
    "shottr"
    "slack"
    "stremio"
    "superwhisper"
    "telegram"
    "unifi-identity-endpoint"
    "visual-studio-code"
    "visual-studio-code@insiders"
    "vlc"
    "wifiman"
  ];
  onActivation.cleanup = "zap";
  onActivation.autoUpdate = true;
  onActivation.upgrade = true;
}
