{
  enable = true;
  taps = [  "manaflow-ai/cmux" "typewhisper/tap" ];
  brews = [
    "agent-browser"
    "choose-gui"
    "cliclick"
    "gemini-cli"
    "jetbrains/junie/junie"
    "jsongrep"
    "sst/tap/opencode"
  ];
  casks = [
    "adobe-creative-cloud"
    "arc"
    "betterdisplay"
    "bettermouse"
    "bitwarden"
    "chatgpt"
    "claude"
    "cloudflare-warp"
    "codex"
    "comfyui"
    "contexts"
    "cursor"
    "displaylink"
    "elgato-camera-hub"
    "elgato-control-center"
    "elgato-stream-deck"
    "elgato-wave-link"
    "figma"
    "ghostty@tip"
    "google-chrome"
    "google-chrome@canary"
    "google-drive"
    "grandperspective"
    "handbrake-app"
    "helium-browser"
    "imaging-edge"
    "jetbrains-toolbox"
    "karabiner-elements"
    "manaflow-ai/cmux/cmux"
    "meld-studio"
    "mqtt-explorer"
    "notion"
    "obs"
    "orbstack"
    "orion"
    "raycast"
    "shottr"
    "slack"
    "stremio"
    "superwhisper"
    "telegram"
    "thebrowsercompany-dia"
    "typewhisper/tap/typewhisper"
    "visual-studio-code"
    "visual-studio-code@insiders"
    "vlc"
    "whatsapp@beta"
    "wifiman"
  ];
  onActivation.cleanup = "zap";
  onActivation.autoUpdate = true;
  onActivation.upgrade = true;
}
