{
  enable = true;
  taps = [ ];
  brews = [
    "asdf"
    "agent-browser"
    "choose-gui"
    "cliclick"
    "gemini-cli"
    "go-task"
    "jsongrep"
    "node@24"
    "sst/tap/opencode"
    "pnpm"
    "herdr"
  ];
  casks = [
    "adobe-creative-cloud"
    "arc"
    "augani/dory/dory"
    "avg-antivirus"
    "bettermouse"
    "bitwarden"
    "chatgpt"
    "claude"
    "cleanshot"
    "cloudflare-warp"
    "cmux"
    "codex"
    "cursor"
    "darrylmorley/whatcable/whatcable"
    "displaylink"
    "elgato-control-center"
    "elgato-stream-deck"
    "elgato-wave-link"
    "figma"
    "ghostty@tip"
    "github-copilot-app"
    "google-chrome"
    "google-drive"
    "grandperspective"
    "handbrake-app"
    "helium-browser"
    "homebrew-app"
    "imaging-edge"
    "ivg-design/tap/sidebarfavorites"
    "jetbrains-toolbox"
    "karabiner-elements"
    "meld-studio"
    "microsoft-teams"
    "notion"
    "obs"
    "raycast"
    "slack"
    "stremio"
    "telegram"
    "thebrowsercompany-dia"
    "visual-studio-code"
    "vlc"
    "vorssaint"
    "whatsapp@beta"
    "wifiman"
  ];
  onActivation.cleanup = "zap";
  onActivation.autoUpdate = true;
  onActivation.upgrade = true;
}
