#!/usr/bin/env bash
set -eo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Downloads a video audio in the current directory
##?
##? Usage:
##?   download-mp3 <url>

youtube-dl -x --audio-format mp3 "$1"
