#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Show all available jdks
#?? 1.0.0
##?
##? Usage:
##?   available_jdks
docs::parse "$@"

ls /Library/Java/JavaVirtualMachines
