#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Show all available commands
#?? 1.0.0
##?
##? Usage:
##?   available_commands
docs::parse "$@"

bash -c "compgen -c"
