#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Delete all dist parameters on the current directory
#?? 1.0.0
##?
##? Usage:
##?    delete_dist_parameters

docs::eval "$@"

find . -type f -name "*parameters.yml.dist" | while read line; do
  rm $(echo ${line} | sed "s/.yml.dist/.yml/")
  echo "$line deleted"
done
