#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Saarch the binary and opens intellij or focus if already opened
#?? 1.0.0
##?
##? Usage:
##?    open_intellij

docs::eval "$@"

toolbox_intellij_dir="$HOME/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0"
intellij_version=$(ls "${toolbox_intellij_dir}" | sort -r | head -n 1)
intellij_folder=$(ls "$toolbox_intellij_dir/$intellij_version" | grep '.app$')
intellij_bin_path="$toolbox_intellij_dir/$intellij_version/$intellij_folder/Contents/MacOS/idea"

open -a "$intellij_bin_path"
