#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Open one common element
#?? 1.0.0
##?
##? Usage:
##?   open_common
docs::parse "$@"

declare -A folders

folders=(
	["⬇️ Downloads"]="$HOME/Downloads"
	["🖥️ Desktop"]="$HOME/Desktop"
	["👨‍💻 Code"]="$HOME/Code/codely"
	["☁️ tmp"]="$HOME/Desktop/tmp"
	["📷 Screenshots"]="$HOME/Desktop/tmp/screenshots"
	["🎥 Screencasts"]="$HOME/Desktop/tmp/screencasts"
	["🤏 Thumbnails"]="$GOOGLE_DRIVE_PATH/Shared drives/👑 Contents/🔖 Pro/Design/Thumbnails Cursos"
	["🔴 Recordings"]="$GOOGLE_DRIVE_PATH/Shared drives/👑 Contents/🔴 Recordings"
	["📽️ Slides cursos"]="BROWSE:$HOME/Library/Mobile Documents/com~apple~CloudDocs/🍍 Codely/Cursos"
)

folder=$(printf "%s\n" "${!folders[@]}" | choose)

if [[ -z $folder ]]; then
	echo "No folder selected"
	exit 0
fi

path="${folders[$folder]}"

if [[ $path == BROWSE:* ]]; then
	browse_path="${path#BROWSE:}"
	selected=$(ls -t "$browse_path" | choose)
	if [[ -n $selected ]]; then
		open "$browse_path/$selected"
	fi
else
	open "$path"
fi
