#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Open one common element
#?? 1.0.0
##?
##? Usage:
##?   open_common
docs::parse "$@"

declare -A folders

folders=(
	["⬇️ Downloads"]="$HOME/Downloads"
	["🖥️ Desktop"]="$HOME/Desktop"
	["☁️ tmp"]="$HOME/Desktop/tmp"
	["📷 Screenshots"]="$HOME/Desktop/tmp/screenshots"
	["🎥 Screencasts"]="$HOME/Desktop/tmp/screencasts"
	["🤏 Thumbnails"]="$GOOGLE_DRIVE_PATH/Shared drives/👑 Contents/🔖 Pro/Design/Thumbnails Cursos"
	["🔴 Recordings"]="$GOOGLE_DRIVE_PATH/Shared drives/👑 Contents/🔴 Recordings"
)

folder=$(printf "%s\n" "${!folders[@]}" | choose)

if [[ -n ${folders[$folder]} ]]; then
    open "${folders[$folder]}"
else
    echo "No folder selected"
fi
