#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Open one common element
#?? 1.0.0
##?
##? Usage:
##?   random
docs::parse "$@"

declare -A commands

commands=(
	["domain"]="faker-cli --internet domainName"
	["email"]="faker-cli --internet email"
	["name"]="faker-cli --names firstName"
	["uuid"]="uuidgen"
)

command=$(printf "%s\n" "${!commands[@]}" | choose)

if [[ -n ${commands[$command]} ]]; then
    eval "${commands[$command]}" | sed 's/"//g' | pbcopy
else
    echo "No command selected"
fi
