#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Restart the soundbar (I dunno why it fails, but this fixes it)
#?? 1.0.0
##?
##? Usage:
##?   restart_soundbar
docs::parse "$@"

uhubctl -l 20-9 -p 3 -a off
uhubctl -l 20-9 -p 3 -a on
