#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Select
#?? 1.0.0
##?
##? Usage:
##?   select <thing>
docs::parse "$@"

case "$thing" in
kbhd)
	tail -f /usr/local/var/log/skhd/skhd.*
	;;

*)
	echo "\`$thing\` not known"
	exit 1
	;;
esac
