#!/usr/bin/env bash

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Some twitter utilites
#?? 1.0.0
##?
##? Usage:
##?   twitter audit
docs::parse "$@"

#https://mobile.twitter.com/search?q=from:Kikenico+exclude:retweets+-filter:replies&src=typed_query
