#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Show all changed files to master
#?? 1.0.0
##?
##? Usage:
##?    git-changed-filed

docs::eval "$@"

git diff --name-only master
