#!/usr/bin/env zsh

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Git log filtering
#?? 1.0.0
##?
##? Usage:
##?    log-pretty

docs::eval_zsh "$0" "$@"

commit=$(git log --graph --color=always --date=human --format="%C(auto)%h%d %s %C(black)%C(bold)%ad by %an" | fzf --ansi --no-sort)
commit_hash=$(echo ${commit}  | awk '{print $2}')

echo ${commit_hash} | tr -d '\n' | pbcopy
