#!/usr/bin/env bash
set -eo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Delay all mp4 video audios in a given directory
##?
##? Usage:
##?   delay_audio <seconds>
docs::parse "$@"

ls | grep mp4 | xargs -I_ ffmpeg -i "_" -itsoffset "$seconds" -i "_" -map 0:v -map 1:a -c copy "_-delayed.mp4"
