#!/usr/bin/env bash
set -eo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Transforms a video to gif
##?
##? Usage:
##?   to-gif <video_path>
##?
docs::parse "$@"

ffmpeg \
  -i "$video_path" \
  -r 15 \
  -vf scale=512:-1 \
  "$video_path.gif"
#  -ss 00:00:00 -to 00:00:01 \
