#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Count files recursives in the current direcory
#?? 1.0.0
##?
##? Usage:
##?   count_files_recursive
docs::parse "$@"

find . -type f -print | wc -l
