#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Create a file with all the involved folders
#?? 1.0.0
##?
##? Usage:
##?   create <filename>
docs::parse "$@"

mkdir -p "$(dirname "$1")" && touch "$1"
