#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Show all broken symlinks in the current directory
#?? 1.0.0
##?
##? Usage:
##?    find_broken_symlinks

docs::eval "$@"

find -L . -type l
