#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Show all broken symlinks in the current directory
#?? 1.0.0
##?
##? Usage:
##?   find_broken_symlinks
docs::parse "$@"

find -L . -type l
