#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Flat the current directory
#?? 1.0.0
##?
##? Usage:
##?   flat_this_dir
docs::parse "$@"

sudo find . -mindepth 2 -type f -exec mv -i '{}' . ';'
