#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Reduce a markdown text to two levels from the clipboard
#?? 1.0.0
##?
##? Usage:
##?   reduce_to_two_levels
docs::parse "$@"

extract_lists() {
  local text="$1"
  echo "$text" | \
    awk 'NF && !/^ {6,}[-\[]/' | \
    sed -E $'s/[✅☑️🎥🖼️]//g' | \
    sed 's/YouTube //g' | \
    sed 's/\xC2\xA0/ /g'
}

extract_lists "$(pbpaste)"
