#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Uninstall brew cask package
#?? 1.0.0
##?
##? Usage:
##?    brew_cask_uninstall

docs::eval "$@"

if [[ -z $1 ]]; then
  to_uninstall=$(brew cask list | fzf)
else
  to_uninstall=$(brew cask list | grep $1 | fzf)
fi

if [[ -z ${to_uninstall} ]]; then
  echo "You haven't selected any package to uninstall! ༼つ◕_◕༽つ"

  exit 1
fi

brew cask uninstall ${to_uninstall}
