#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Install brew cask package
#?? 1.0.0
##?
##? Usage:
##?    brew_cask_install

docs::eval "$@"

if [[ -z $1 ]]; then
  package=$(brew search --cask | fzf)
else
  package=$(brew search --cask | grep $1 | fzf)
fi

if [[ -z ${package} ]]; then
  echo "You haven't selected any package to install! ༼つ◕_◕༽つ"

  exit 1
fi

brew cask install ${package}
