#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Export all installed packages
#?? 1.0.0
##?
##? Usage:
##?    export

docs::eval "$@"

brew services stop --all

brew bundle dump --file=${HOMEBREW_BUNDLE_FILE_PATH} --force

echo 'Brew apps exported!'
