#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Sync all installed packages (previously exported)
#?? 1.0.0
##?
##? Usage:
##?   export
docs::eval "$@"

#brew services stop --all
#brew bundle dump --file="$HOMEBREW_BUNDLE_FILE_PATH" --force
#echo 'Brew apps imported!'

pip install -r "$DOTFILES_PATH/langs/python/requirements.txt"
echo 'Python apps imported!'

xargs -I_ npm install -g "_" <"$DOTFILES_PATH/langs/js/global_modules.txt"
echo 'NPM apps imported!'

dot package export
