#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Update all packages
#?? 1.0.0
##?
##? Usage:
##?   update_all [--all]
docs::eval "$@"

echo '🍎 Updating App Store apps'
mas upgrade

echo ''
echo '🍺 Updating Brew apps'
brew update >/dev/null
brew outdated | xargs -n1 brew upgrade

echo ''
echo '🍻 Updating Brew Cask apps'
OUTDATED_CASKS=$(brew cask outdated)

if [ -n "$OUTDATED_CASKS" ]; then
  echo "$OUTDATED_CASKS" | grep -v real-vnc | xargs -n1 brew cask install --force
  echo '✅ Casks updated'
else
  echo '✅ Casks already up-to-date'
fi

echo ''
echo '⚡️ System: Symlinks, Zim…'
dot self update

echo ''
echo '📜 tldr'
tldr --update

if [ "${1-none}" == "--all" ]; then
  echo ''
  echo '🐘 Updating Composer (PHP)'
  composer global update

  echo ''
  echo '🐍 Updating Pip (Python)'
  pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip3 install -U

  echo ''
  echo '♦️ Updating gem (Ruby)'
  gem update

  echo ''
  echo '🌈 Updating npm (JS)'
  npm install -g npm
  npm update -g
fi
