#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Show usage examples for a command
#?? 1.0.0
##?
##? Usage:
##?   tldr <command>...
docs::parse "$@"

dot claude cc \
  --model "haiku" \
  --append-system-prompt 'El output se mostrará directamente en una terminal, así que:
- Responde con texto sin formatear.
- MUY IMPORTANTE: No uses formato markdown NI backticks.
- Usa ejemplos y títulos claros.' \
  -p "Dame 3 ejemplos de uso para el comando ${command[*]}."
