#!/usr/bin/env bash

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? ZSH helpers
#?? 1.0.0
##?
##? Usage:
##?   zsh optimize
##?   zsh test_performance
##?   zsh reload_completions
docs::eval "$@"

case $1 in
"optimize")
  find "$DOTFILES_PATH/shell/zsh" -name '*.zwc' -exec rm -rf {} \;
  find "$DOTFILES_PATH/shell/zsh" -name '*.old' -exec rm -rf {} \;
  find "$DOTFILES_PATH/modules/zimfw" -name '*.zwc' -exec rm -rf {} \;
  find "$DOTFILES_PATH/modules/zimfw" -name '*.old' -exec rm -rf {} \;

  /bin/zsh -c "source ${ZDOTDIR:-${HOME}}/.zlogin"

  dot shell zsh reload_completions
  ;;
"test_performance")
  echo "With native macOS ZSH /bin/zsh"
  /bin/zsh --version
  for i in $(seq 1 10); do /usr/bin/time /bin/zsh -i -c exit; done
  echo ""
  echo "With Brew ZSH /usr/local/bin/zsh"
  /usr/local/bin/zsh --version
  for i in $(seq 1 10); do /usr/bin/time /usr/local/bin/zsh -i -c exit; done

  echo ""
  echo "Currently using $(command -v zsh)"
  ;;
"reload_completions")
  echo "Now execute (copied to your clipboard):"
  echo "autoload -U compaudit && autoload -Uz compinit && compinit"
  echo -n "autoload -U compaudit && autoload -Uz compinit && compinit" | pbcopy
  ;;
*)
  exit 1
  ;;
esac
