alias p='pwd'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias ll='exa -l'
alias lo='exa -l --sort=old'
alias la='exa -la'
alias lf='ls -d */'
alias ctree='exa -T'
alias j='z'

# Jumps
alias tmp='cd ~/Desktop/tmp'
alias ccc='cd ~/Code'
alias mines='cd ~/Code/mines'
alias codely='cd ~/Code/codely'
alias dotfiles='cd ~/.dotfiles'
