alias p='pwd'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias ..2='cd ../..'
alias ..3='cd ../../..'
alias ..4='cd ../../../..'
alias ll='exa -l'
alias lo='exa -l --sort=old'
alias la='exa -la'
alias lf='ls -d */'
alias ctree='exa -T'
alias j='z'

# Jumps
alias tmp='cd /tmp'
alias code='cd ~/Code'
alias mines='cd ~/Code/mines'
alias codely='cd ~/Code/codely'
alias dotfiles='cd ~/.dotfiles'
