alias gaa='git add -A'
alias gc='git c'
alias gca='git add --all && git commit --amend --no-edit'
alias gcae='git add --all && git commit --amend'
alias gco='git checkout'
alias gd='git diff --color'
alias gs='git status -sb'
alias gf='git fetch --all -p'
alias gps='git push'
alias gpsf='git push --force-with-lease'
alias gpl='git pull --rebase --autostash'
alias gpom='git pull origin master --rebase --autostash'
alias gpum='git pull upstream master --rebase --autostash'
alias gb='git branch'
alias gundo='git undo'
grn() { git rebase -i HEAD~"$1"; }
