alias gaa='git add -A'
alias gc='git c'
alias gca='git add --all && git commit --amend --no-edit'
alias gco='git checkout'
alias gd='git diff --color'
alias gs='git status -sb'
alias gf='git fetch --all -p'
alias gps='git push'
alias gpl='git pull --rebase --autostash'
alias gpom='git pull origin master --rebase --autostash'
alias gb='git branch'
grn() { git rebase -i HEAD~"$1"; }
