alias phprepl='psysh'
alias phpunit='./vendor/bin/phpunit --colors'
alias pf='./vendor/bin/phpunit --filter'
alias behat='./vendor/bin/behat'
alias bf='./vendor/bin/behat --tags=~skip --tags=~skip -p'
alias bfp='./vendor/bin/behat --tags=~skip --format=progress -vvv --tags=~skip -p'
alias cr='composer require --ignore-platform-reqs'
