#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? List the top stargazers for a repository
#?? 1.0.0
##?
##? Usage:
##?    top_stargazers <repo>
##?
##? Example:
##?    top_stargazers rgomezcasas/dotfiles

docs::eval "$@"

log::warning "This could take a while!"

repo_name=${repo/\//_}
path="$(mktemp -d -t gh_repo_stargazers)/$repo_name.csv"

log::note "CSV will be created in $path"

python2 "$DOTFILES_PATH/scripts/github/utils/repo_stargazers.py" -t "$GITHUB_TOKEN" -p "$path" -r "$repo"

table::print "," "$(csvsort -r -c num_followers $path)"
