#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Clean junk files
#?? 1.0.0
##?
##? Usage:
##?   clean
docs::parse "$@"

sudo find /usr/local/Cellar/python* -name "IDLE*.app" -exec rm -rf "{}" \;
echo '[x] Python junk cleaned'

echo 'Done!'
