#!/usr/bin/env bash

##? Consolidated cron script that runs every 15 seconds
##?
##? Usage:
##?   cron

set -euo pipefail

source "$DOTLY_PATH/scripts/core/log.sh"

main() {
    "$DOTFILES_PATH/scripts/system/sdot" mac toggle_menu_bar > /dev/null 2>&1 || true
    "$DOTFILES_PATH/scripts/system/sdot" network check_wifi_when_ethernet > /dev/null 2>&1 || true
}

main "$@"
