#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Empty the trash and remove cache files
#?? 1.0.0
##?
##? Usage:
##?   empty_trash
docs::parse "$@"

free_space_in_home() {
	df -h ~ | tail -n1 | awk '{print $4}'
}

free_space_before_empty=$(free_space_in_home)

rm -rf ~/Library/Caches/* 2>/dev/null || true
echo '📦 All caches cleared'

sudo rm -rfv /private/var/log/asl/*.asl
sudo rm -rfv /var/log/asl/*.asl
echo '📜  Mac logs empty'

sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'
echo '⏬  Mac downloads history empty'

rm -rf "$HOME/Movies/"*.fcpbundle"/"*"/Render Files/High Quality Media"
echo '🎬  Final Cut rendered media cleared'

brew cleanup
brew cleanup --prune-prefix
echo '🍺  Brew cache cleared'

rm -rf ~/Library/Application Support/Slack/Cache
rm -rf "$HOME/Library/Application Support/Slack/Service Worker/CacheStorage"
echo '💬  Slack cache cleared'

rm -rf .npm/_cacache/
rm -rf .npm/_npx/
echo '💪  NPM cache cleared'

find "$HOME/Code" -type d -path "*/.next/cache" -exec rm -rf {} \; -prune
echo '💪  Next.js cache cleared'

rm -rf "$HOME/Library/Application Support/com.turborepo.turborepo/logs"
find "$HOME/Code" -type d -path "*/.turbo/cache" -exec rm -rf {} \; -prune
echo '💨 Turborepo logs & cache cleared'

find "$HOME/Code" -type d -path "*/node_modules" -exec rm -rf {} \; -prune
echo '💪  node_modules cleared'

rm -rf ~/.gradle/wrapper/dists/
rm -rf ~/.gradle/caches/
echo '🐘  Gradle cache cleared'

rm -rf ~/.composer/cache/
echo '👨‍🎤  Composer cache cleared'

rm -rf "$HOME/Library/Application Support/Google/Chrome/"*"/Service Worker/CacheStorage" || true
rm -rf "$HOME/Library/Application Support/Google/Chrome/"*"/Application Cache/Cache" || true
echo '🟡  Chrome cache cleared'

rm -rf Library/Application\ Support/stremio-server/stremio-cache/
echo '📺  Stremio cache cleared'

osascript -e 'tell app "Finder" to empty' 2>/dev/null || true
echo '🗑   All trashes empty'

free_space_after_empty=$(free_space_in_home)

echo "Done! Free space before: $free_space_before_empty, free space now: $free_space_after_empty"
