#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Prints the owner for a port
#?? 1.0.0
##?
##? Usage:
##?   port_owner <port>
docs::parse "$@"

lsof -n -i4TCP:$1 | grep LISTEN
