#!/usr/bin/env bash

export DOTFILES_PATH="$HOME/.dotfiles"
export DOTLY_PATH="$DOTFILES_PATH/modules/dotly"
export PATH="$HOME/.cargo/bin:/run/current-system/sw/bin:/usr/bin:/usr/sbin:/bin:/sbin:/opt/homebrew/bin:$PATH"

for export_file in "$DOTFILES_PATH"/modules/private/shell/exports.sh; do
  [ -f "$export_file" ] && source "$export_file"
done

##? dot, but without environment variables
##?
##? Same usage as dot

"$DOTLY_PATH/bin/dot" "$@"
