#!/usr/bin/env bash

export DOTFILES_PATH="$HOME/.dotfiles"
export DOTLY_PATH="$DOTFILES_PATH/modules/dotly"
export PATH="$HOME/.cargo/bin:/run/current-system/sw/bin:/usr/bin:/usr/sbin:/bin:/sbin:/opt/homebrew/bin:$PATH"

private_exports="$DOTFILES_PATH/modules/private/shell/exports.sh"
[ -f "$private_exports" ] && source "$private_exports"

##? dot, but without environment variables
##?
##? Same usage as dot

"$DOTLY_PATH/bin/dot" "$@"
