#!/usr/bin/env bash

export DOTFILES_PATH="$HOME/.dotfiles"
export DOTLY_PATH="$DOTFILES_PATH/modules/dotly"
export PATH="/run/current-system/sw/bin:/usr/bin:/usr/sbin:/bin:/sbin:/opt/homebrew/bin:$PATH"

##? dot, but without environment variables
##?
##? Same usage as dot

"$DOTLY_PATH/bin/dot" "$@"
