#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Show open files by an app
#?? 1.0.0
##?
##? Usage:
##?   show_app_open_files
##?   show_app_open_files --watch
##?
##? Options:
##?   -h --help   Show this screen.
##?   -w --watch  Watch the changes
docs::parse "$@"

selected=$(dot system list_opened_apps | fzf)

if $watch; then
  lsof -r 2 -c "$selected" | awk '{print $4 " " $9}'
else
  lsof -c "$selected" | awk '{print $4 " " $9}'
fi
