#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Update system packages and shell plugins
#?? 1.0.0
##?
##? Usage:
##?   update
docs::parse "$@"

nix flake update --flake "$DOTFILES_PATH/config/nix"
git -C "$DOTFILES_PATH" add config/nix/flake.lock
git -C "$DOTFILES_PATH" commit -m "chore(nix): update flake.lock"
nvd diff $(ls -dt /nix/var/nix/profiles/system-*-link | head -n2)
sudo darwin-rebuild switch --flake "$DOTFILES_PATH/config/nix#pro" --impure
zimfw upgrade
