#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"
source "$DOTFILES_PATH/scripts/self/utils/install.sh"

##? Install the dotfiles
#?? 1.0.0
##?
##? Usage:
##?    install

docs::eval_help "$@"

"$DOTFILES_PATH/bin/dot" self update

if platform::is_macos; then
  log::note "Installing MacOS  custom packages"

  install_macos_custom
fi

if platform::is_linux; then
  log::note "Installing Linux 🐧 custom packages"

  install_linux_custom
fi

log::note "Setting ZSH as the default shell"
chsh -s "$(command -v zsh)"

read -rp "🦑 Git config: What is you email? " git_email
read -rp "🐙 Git config: And your name? " git_name

git config --global user.email "$git_email"
git config --global user.name "$git_name"
git config --global --unset user.signingkey
git config --global --unset commit.gpgsign
git config --global --unset tag.gpgsign
git config --global --unset gpg.program

log::warning "Remember to add the origin of your fork!"
