#!/usr/bin/env bash

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Disable airpods microphone if whitelisted mic are connected
#?? 1.0.0
##?
##? Usage:
##?   disable_airpods_microphone
docs::parse "$@"

allowed_mics=(
	"Shure MV7"
)

all_mics=$(SwitchAudioSource -a -t input)

current_mic_is_airpods=$(SwitchAudioSource -c -t input | grep -i "AirPods")

if [ -n "$current_mic_is_airpods" ]; then
	for mic in "${allowed_mics[@]}"; do
	if echo "$all_mics" | grep -i "$mic" > /dev/null; then
		SwitchAudioSource -t input -s "$mic" > /dev/null
		terminal-notifier -message "Enabling $mic" -title "AirPods mic disabled" -group "im.rafa.mic"
		sleep 3
		terminal-notifier -remove "im.rafa.mic"
		exit 0
	fi
	done

	echo "No allowed mic found, keeping AirPods mic enabled"
fi
