#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? List launch items dirs
#?? 1.0.0
##?
##? Usage:
##?   list_launch_items_dirs
##?
##? Options:
##?   -h --help       Show this screen.
docs::parse "$@"

echo "💂‍ User"
echo "/Library/LaunchDaemons"
echo "/Library/LaunchAgents"
echo "$HOME/Library/LaunchAgents"
echo
echo "🔒 System"
echo "/System/Library/LaunchDaemons"
echo "/System/Library/LaunchAgents"
echo
echo "👌 TIPs"
echo "To see all, execute: launchctl list"
echo 'To disable one, execute: launchctl unload $AGENT'
