#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Ensure menu bar is visible only when there is one screen.
#?? 1.1.0
##?
##? Usage:
##?   sync_menu_bar_visibility
docs::parse "$@"

function get_total_screens() {
  system_profiler SPDisplaysDataType | grep -c "Resolution"
}

function is_menu_bar_hidden() {
  defaults read NSGlobalDomain _HIHideMenuBar
}

function toggle_menu_bar() {
  open -g "raycast://extensions/iamyeizi/toggle-menu-bar/toggle"
}

monitors_file="$HOME/.dotly__total_monitors"
total_screens=$(get_total_screens)

if ! [[ -f "$monitors_file" ]]; then
  echo "0" > "$monitors_file"
fi

previous_total_screens=$(cat "$monitors_file")

if [[ "$total_screens" -eq "$previous_total_screens" ]]; then
  exit 0
fi

echo "$total_screens" > "$monitors_file"

is_menu_bar_hidden=$(is_menu_bar_hidden)
should_be_hidden=$((total_screens > 1))

if [[ "$is_menu_bar_hidden" -ne "$should_be_hidden" ]]; then
  toggle_menu_bar
fi
