#!/usr/bin/env bash

echo '♢ Outdated App Store apps:'
mas outdated

echo ''
echo '♢ Outdated brew apps:'
brew update >/dev/null
brew outdated

echo ''
echo '♢ Outdated brew cask apps:'
brew cask outdated | grep -v real-vnc
