#!/usr/bin/env bash

# --- About this script ---
# In order to have emoij support I needed to copy and paste with applescript instead of
# using `pbcopy`

#dictionary_path=$1
#separator=$2
dictionary_path="/Users/rafa.gomez/Google Drive/Me/Other/autocompletion.txt"
separator="->"

autocomplete_abbrev=()
autocomplete_text=()

__trim() {
    local var="$*"
    var="${var#"${var%%[![:space:]]*}"}"
    var="${var%"${var##*[![:space:]]}"}"
    echo -n "$var"
}

while read -r line; do
  IFS=$'\2' read -r -a arr <<<"${line//"$separator"/$'\2'}"

  autocomplete_abbrev+=("$(__trim "${arr[0]}")")
  autocomplete_text+=("$(__trim "${arr[1]}")")
done <"$dictionary_path"

selected=$(printf '%s\n' "${autocomplete_abbrev[@]}" | /usr/local/bin/choose -i -c highlight=000000)

clicked_text="$(echo -n "${autocomplete_text[$selected]}")"

/usr/bin/osascript -e 'set the clipboard to "'"$clicked_text"'"'

/Users/rafa.gomez/.dotfiles/scripts/osx_paste_from_clipboard
