#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Complete with OpenAI an response the clipboard content
#?? 1.0.0
##?
##? Usage:
##?   complete
docs::parse "$@"

clipboard_content="$(pbpaste)"

response=$(curl -s 'https://api.openai.com/v1/completions' \
	-X POST -H "Content-Type: application/json" \
	-H "Authorization: Bearer $OPENAI_API_KEY" \
	--data-binary "{\"model\":\"text-davinci-003\",\"prompt\":\"$clipboard_content\",\"temperature\":0,\"max_tokens\":256}")

echo "Curl hecho"
echo "$response"
