#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Detect face age
#?? 1.0.0
##?
##? Usage:
##?   deepface <image__path>
docs::parse "$@"

source "$HOME/miniforge3/bin/activate"

python "$DOTFILES_PATH/scripts/ai/utils/face_recognition.py" "$1"
