#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Paste the selected prompt
#?? 1.0.0
##?
##? Usage:
##?   prompt
docs::parse "$@"

prompts_dir="$DOTFILES_PATH/modules/private/prompts"
prompt=$(ls -1 "$prompts_dir" | choose)

cat "$prompts_dir/$prompt" | pbcopy

dot mac paste_text -n
