alias ga='git add -A'
alias gc='git c'
alias gn='git n'
alias gam='git amend'

alias gco='git checkout'
alias gd='git diff --color'
alias gs='git status -sb'
alias gf='git fetch --all -p'
alias gp='git push'
alias gfp='git push -f'
alias gpull='git pull'
alias gmm='git merge master'
alias gpom='git pull origin master'
alias gpum='git pull upstream master'
alias gb='git branch'
alias gdb='git branch -D'
